apiVersion: v1
kind: Service
metadata:
  name: mcp-global-api
  labels:
    app: mcp-global-api
spec:
  type: ClusterIP
  selector:
    app: mcp-global-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
